version: "3.1"
services:
    www:
        build: .
        ports: 
            - "9000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - frontend
            - backend
    db:
        image: mysql:8.0
        ports: 
            - "3308:3308"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dockerExample
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 9001:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        networks:
            - frontend
            - backend

volumes:
    persistent:

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
